### ISSUE TITLE
Need multiple codes for a concept

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr_spec#12]
Example:
Concept:		LNC #45392-8, SCT #408677003

**Comment by gregquinn2001** [comment]
Is this because they have different codes in each such that the concept would be incomplete with only one? Can we define an SHR value set that combines them into one code set by reference then? Also, are there common codes between the 2 sets? If so, can we combine the 2 code sets by reference and indicate some specific codes or code ranges should not be included?

**Comment by markkramerus** [comment]
Codes would be synonyms. Synonyms are useful computationally. Multiple codes can be represented by FHIR CodeableConcept. 
Another example is code for blood pressure combined with a code for vital signs.

**Comment by gregquinn2001** [comment]
If they are synonyms, let's just support one so implementations only have to check for 1 and can't just check for one and lose interoperability with ones that use the other. Synonyms are the enemy of computability because they allow for variability for the sake of variability. You're citing what FHIR does as an example of what we should be doing? Let's just use FHIR as is then!

**Comment by markkramerus** [comment]
Greg, it is a more complex conversation, we should talk. Remember there are two things being coded, the Question and the Answer. In short, I don't accept that synonyms for the **Question** (aka the concept) inhibits interoperability. We should have a preferred code that everyone should use. But synonyms might help more users can understand the topic of the message. You might even tag a message with non-synonymous tags, for example, labeling a concept not only as a blood pressure, but also as a vital sign. This helps in information retrieval if you want to populate a vital sign section. I'm open for discussion.

**Comment by cmoesel** [comment]
This is related (possibly a duplicate) of #9.

**Comment by markkramerus** [comment]
Going to close this, since it hasn't elevated above the theoretical. We're not going to address it unless there is a real need.
