### ISSUE TITLE
multiple bindings 

### ISSUE THREAD

**Issue by parisni** [standardhealth/shr_spec#36]
Hi,

ProviderRelationship.HealthcareRole defines 2 possible codeable concepts (http://standardhealthrecord.org/shr/actor/#HealthcareRole)
However the resulting FHIR profile gets only one (the first one) because FHIR does not accept multiple binding
http://standardhealthrecord.org/fhir/StructureDefinition-shr-actor-ProviderRelationship.html

Am I missing something ?

Thanks

**Comment by cmoesel** [comment]
Thanks for reporting this.  At one point we had hoped we could model multiple bindings in FHIR using a choice, but since the binding goes directly on the `ElementDefinition` rather than `ElementDefinition.type`, this is not possible.

In order to accomplish what's being attempted here, we'll likely have to create a new value set that contains both of the value sets indicated in HealthcareRole.  I'll speak with the author of this data element to get his opinion.

I've also noted that this is an area in which the tooling should generate an error so that we can catch these types of issues before you do!

**Comment by cmoesel** [comment]
We've recently pushed an update to the SHR definitions that removes the cases where we had multiple bindings.  In addition we now produce warning and/or errors when the FHIR exporter detects attempts at multiple bindings (in the [shr-fhir-export 4.2.2 release](https://github.com/standardhealth/shr-fhir-export/releases/tag/v4.2.2) and the [shr-cli 4.3.2 release](https://github.com/standardhealth/shr-cli/releases/tag/v4.3.2)).
