### ISSUE TITLE
Binding strength SHR -> FHIR

### ISSUE THREAD

**Issue by parisni** [standardhealth/shr_spec#37]
Hi

FHIR' Encounter.class binding is "Extensible" (https://www.hl7.org/fhir/terminologies.html#extensible / https://www.hl7.org/fhir/encounter.html)

SHR mapping to Encounter.class binds http://standardhealthrecord.org/fhir/ValueSet-shr-encounter-EncounterTypeVS.html that does not extend https://www.hl7.org/fhir/v3/ActEncounterCode/vs.html but totally replace it. 

It looks not conform to FHIR specification ?

Thanks

**Comment by cmoesel** [comment]
Thanks for reporting this.  Our tooling currently prohibits overriding _required_ value sets, but is more lenient on _extensible_ value sets.  FHIR does allow [overriding extensible value sets in profiles](https://www.hl7.org/fhir/profiling.html#tx), but only if there are not codes with overlapping meanings.  The example you cite above clearly _does_ have codes with overlapping meanings.

Our tooling and FHIR's tooling doesn't prohibit this use case since it would be very difficult for the tooling to be able to determine if a code has overlapping meaning or not -- so the tools give the authors the benefit of the doubt.  That said, our tooling should ideally at least generate a warning when overriding an extensible value set so that the author can take a look and confirm they're not violating the principal of no overlapping code meanings.

We'll take a look at this in general, but also specifically fix the instance which you've noted above.

**Comment by cmoesel** [comment]
We've recently pushed an update to the SHR definitions that adopts (rather than overrides) FHIR's extensible bindings.  In addition we now produce warnings so authors are aware when they override extensible bindings (in the [shr-fhir-export 4.2.2 release](https://github.com/standardhealth/shr-fhir-export/releases/tag/v4.2.2) and the [shr-cli 4.3.2 release](https://github.com/standardhealth/shr-cli/releases/tag/v4.3.2)).
