### ISSUE TITLE
SHR Element labels Upper Case

### ISSUE THREAD

**Issue by parisni** [standardhealth/shr_spec#38]
Hi

It seems the element label need to have a first letter as UpperCase.  In case I add birthDate to PersonOfRecord, I get the folowing error: 

```
node . ../shr_spec/spec/ -l error
[22:41:09.937Z] ERROR shr: no viable alternative at input 'birthDate' (module=shr-text-input, file=../shr_spec/spec/shr_demographics.txt, line=16, column=7)
[22:41:09.945Z] ERROR shr: mismatched input 'birthDate' expecting {null, null} (module=shr-text-input, file=../shr_spec/spec/shr_demographics.txt, line=32, column=14)
/app/edsr/projets/EDSI/REA/shr/shr-cli/node_modules/shr-text-import/lib/listener.js:241
    if (ctx.elementWithConstraint()) {
           ^

TypeError: Cannot read property 'elementWithConstraint' of undefined

```

Changing it to "**B**irthDate" does the trick.
Most FHIR element labels begin with a lower case. As a result, CAMEO does not allow to use FHIR element "as it is". Why:
- not allowing using the same elements as FHIR
- resulting in changing the names of the element that are mapped (birthDate -> DateOfBirth and sometimes BirthSex and not SexOfBirth BTW)

Thanks for your answer

**Comment by cmoesel** [comment]
In SHR/CAMEO, lowercase names are reserved for primitives only (e.g., boolean, integer, etc.)  FHIR employs a similar convention for data types: primitives are lower case and all other data types are upper case.  FHIR resources are also always upper case (although I'm not sure if that's just a convention or if it's enforced).

What you're referring to as element labels act more like class properties in FHIR -- they are scoped within the namespace of a resource (or, more accurately, a specific StructureDefinition) and are not re-usable (as definitional elements) outside of that scope.  SHR/CAMEO takes a different approach by making _everything_ a re-usable element and composing them together to make more complex elements.  In this way, your BirthDate element in SHR is more like a re-usable _class_ than FHIR's Patient.birthDate property is.  This distinction is most likely what led us to feel that capitalizing elements felt more natural (since many programming languages capitalize class names).

I'll admit that outside of the formal CAMEO grammar, this probably is not documented well.

Regarding "not allowing using the same elements as FHIR", the tie to FHIR happens in the mapping file, where you'll find things like:
```
PersonOfRecord maps to Patient:
    HumanName maps to name
    DateOfBirth maps to birthDate
    ....
```

As to why we call it `DateOfBirth` rather than `BirthDate` (to more closely match the FHIR property name), I'm not entirely sure.  Perhaps @markkramerus can chime in.  When building the initial SHR model, we looked at many other modeling frameworks as well (not just FHIR) and it's possible that this phrasing was found often in other models.  But like I said, I'm not sure -- Mark might be able to answer better.

**Comment by cmoesel** [comment]
BTW -- to further illustrate the difference between SHR's `DateOfBirth` and FHIR's `birthDate`, note that SHR's Patient, Practitioner, RelatedPerson, and Person elements all reference the _same_ `DateOfBirth` element.   They are semantically linked.  On the other hand, FHIR's Patient, Practitioner, RelatedPerson, and Person resources all have `birthDate` properties, but the details of each property are independently defined -- and aside from the fact that they have the same name (which is _not_ a reliable indicator), there isn't a formal link between them.

**Comment by parisni** [comment]
Thanks.

The reason I d'like to be able to write in lower case would be
```
PersonOfRecord maps to Patient:
    name maps to name
    birthDate maps to birthDate
```

In order to get the html documentation you generate in accordance with the resulting FHIR resources. I also wonder why you choose to use different names for SHR' elements when they map to FHIR. This is a  bit confusing to introduce new elements terms when you could have used the same.

I may go for something like that:
```
PersonOfRecord maps to Patient:
    Name maps to name
    BirthDate maps to birthDate
```
As a result, the SHR resulting html documentation will describe the resulting FHIR resources

**Comment by cmoesel** [comment]
> In order to get the html documentation you generate in accordance with the resulting FHIR resources.

I'm not sure I understand what you mean by this.  Do you mean that you want the PersonOfRecord profile to have its `name` property have the original type (`HumanName`) rather than have type `SHR HumanName Profile`?

> I also wonder why you choose to use different names for SHR' elements when they map to FHIR.

Some of this may be intentional.  For example: When developing SHR elements, we look to several existing specifications and data element dictionaries (not just FHIR).  Sometimes we choose the more common phrasing, even if it is not what FHIR chose.  Or sometimes we name things to maintain consistency within the spec (if the SHR already has many `DateOf[X]` elements, then we might opt for `DateOfBirth` over `BirthDate`).  On the other hand, there may be some cases where the different name is not necessarily intentional and perhaps should be considered for renaming to align more closely with FHIR.

In the end, however, the name should not _technically_ matter as long as the mapping to the underlying FHIR resource/property is correct.  For example, `PersonOfRecord.DateOfBirth` maps cleanly to FHIR's `Patient.birthDate` -- and if you look at the resulting profile, you'll see that `Patient.birthDate` remains `birthDate` and does not have to take on the SHR `DateOfBirth` name.

**Comment by markkramerus** [comment]
Not much separates Birthdate or DateOfBirth except the latter is more clearly a Date, and aligns better with naming of other Dates, such as DateOfDeath (there is no Deathdate).
