### ISSUE TITLE
shr resource instances validation

### ISSUE THREAD

**Issue by parisni** [standardhealth/shr_spec#40]
Hi

I am trying to validate shr resources (built from synthea, eg: Patient). I use the org.hl7.fhir.validator.jar official tool https://www.hl7.org/fhir/validation.html#jar )
My goal, is to test if the value sets, extensions of the resource instance are well formed.
```
java -jar org.hl7.fhir.validator.jar person.json -defn definitions.xml.zip.2 -ig http://standardhealthrecord.org/fhir/ -profile http://standardhealthrecord.org/fhir/StructureDefinition/shr-demographics-PersonOfRecord
  .. load FHIR from definitions.xml.zip
  .. connect to tx server @ http://tx.fhir.org/r3
    (vnull-null)
+  .. load IG from http://standardhealthrecord.org/fhir/
  .. validate
*FAILURE* validating person.json:  error:1 warn:0 info:0
  Fatal @ Patient (line 1, col2) : This does not appear to be a FHIR resource (unknown name 'Patient')
```
Have you ever been using this kind of validation tool before ?

Thanks

**Comment by cmoesel** [comment]
I've not attempted to validate instances against the profiles myself, although some of my colleagues have.  That said, I'm not sure if they used the validator jar provided by the FHIR team or one of the other open source validators available.

I'll check into it.

**Comment by parisni** [comment]
Finally, I got it work (http://community.fhir.org/t/validation-with-custom-profile/365/11).
I was able to validate: 
- my own profiles
- resources
    - FHIRpath (http://hl7.org/fhirpath/index.html)
    - cardinality
    - presence/absence of element/extension

Also I have been able to find some problems in the some synthea resources. I think the official hl7 validation tool could be usefull for your projects

**Comment by cmoesel** [comment]
Thank you.  I believe the Synthea resources have been validated using a ruby-based validator.  If the official FHIR validator is turning up issues that the Ruby one did not, I'm sure the Synthea team would like to know.

Can you please log a more detailed issue w/ Synthea so they can take a look?https://github.com/synthetichealth/synthea

I'm closing this issue since you indicated you were able to validate.  Thanks for the link with the tip as well.
