### ISSUE TITLE
Where do I capture recurrence date?

### ISSUE THREAD

**Issue by gregquinn2001** [standardhealth/shr_spec#45]
I create a BreastCancer entry with WhenClinicallyRecognized set to the diagnosis date and the ClinicalStatus set to recurrence but where can I record when recurrence was clinically recognized?

**Comment by rutemartins** [comment]
@gregquinn2001 I know it's been a long time since you opened this ticket, but I'm wondering how you've addressed this in FluxNotes.

My understanding is that the recurrence of a condition would be captured as another condition instance, but with a `clinicalStatus` of `recurrence`. This obviously has the downside that the original condition and its recurrence are only implicitly connected.

**Comment by gregquinn2001** [comment]
@rutemartins we really don't fully handle it right now as we have no test patients/scenarios involving recurrence. The UI has a recurrence date shown but it's either N/A (if clinical status is not recurrence) or missing (if clinical status is recurrence)

**Comment by markkramerus** [comment]
Closed transferred to MCODE-103 on the Jira board
