### ISSUE TITLE
Should we have a list of identifiers in PersonOfRecord for capturing other identifiers

### ISSUE THREAD

**Issue by gregquinn2001** [standardhealth/shr_spec#46]
e.g. MRN. need a value set of the identifier type. For example, the EHR-specific identifier for a patient could be put and kept with a patient record in SHR form to allow later updating without matching

**Comment by markkramerus** [comment]
Greg, can you expand on this a bit. I don't understand.

**Comment by gregquinn2001** [comment]
This provides a way for legacy systems to store their patient identifier within a patient's record or the identifier of another system in the patient record to avoid the need to create separate storage to map identifiers between systems. Ideally all systems would use shrId but we know that won't happen due to legacy systems and other reasons. A patient will have multiple identifiers so we should just embrace that situation and support multiple identifiers to hopefully maximize interoperability and make patient matching as easy as possible.

**Comment by jgibson** [comment]
Hi Greg, thanks for filing this because I just discovered that we'll need patient identifiers for the curation study. I've found that we need not just a single MRN, but multiple MRNs for a patient because different portions of the same organization use different MRNs for the same patient.

My first thought is that the MRN would subclass `Identifier` and have it also contain a reference to the issuing organization. Patient would have`0..*` MRNs.

The only wrinkle that I thought of was if we need to track the issuing of MRNs to an existing patient as a patient moves through the healthcare system as new SHR records or if we can just update the existing `Patient` object.

**Comment by rutemartins** [comment]
At one point `Patient` had `0..* ref(ExternalHealthRecord)`, which seems to fit the need, although there isn't a mechanism to flag a master identifier across these. I noticed in the latest code, this has been commented out. @markkramerus should we revisit this?

And @jgibson how did you end up addressing this for the curation study?

**Comment by markkramerus** [comment]
Fixed some time ago. Identifier allows multiple values.
