### ISSUE TITLE
What should FocalSubject reference for a PersonOfRecord?

### ISSUE THREAD

**Issue by gregquinn2001** [standardhealth/shr_spec#48]
PersonOfRecord is an EntryElement which indicates it has a FocalSubject (from Entry) which should reference the PersonOfRecord this entry is about. Circular so how should we handle this? FocalSubject is required (1..1) in Entry

**Comment by markkramerus** [comment]
This was a placeholder for FamilyHistory where the subject of inquiry (e.g. mother) is someone other than the patient, yet the record belongs to the PersonOrRecord. I'm going to cut this out for now, since this doesn't align well with FHIR. (PS - I don't see it as a circularity. The Entry would simply have PersonofRecord = JoeDoe, FocalSubject = JaneDoe. )

**Comment by gregquinn2001** [comment]
So what change are you making here? You are deleting focalSubject?

**Comment by markkramerus** [comment]
Yes, at least for now.
