### ISSUE TITLE
Does LNC#LA11884-6 "Indeterminate" belong in NottinghamCombinedGradeNullVS?

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/shr_spec#99]
Resolution of ballot comment  [16116](https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=16116&start=0) says yes (although it refers to the local code from `ExceptionValueVS`). However, this code is not part of the normative answer list for the associated [LNC#44648-4](https://s.details.loinc.org/LOINC/44648-4.html?sections=Comprehensive).

Is there a reason why this code was explicitly included in the NottinghamCombinedGradeNullVS?

"Score cannot be determined" is already part of the [normative answer list](https://r.details.loinc.org/AnswerList/LL4561-8.html). As a side note, CAP is the original source of the LOINC code and they have strong reservations with the use of "indeterminate" as defined by NCI and HL7, because they focus on (or include) the notion of distinction between values. In their forms, CAP uses only "cannot be determined".

[Indeterminate, according to NCI](https://nciterms.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&version=18.06d&ns=ncit&code=C48658&key=n1047140876&m=1&b=1&n=null): _Cannot distinguish between two or more possible values in the current context._ NCI lists "cannot be determined" as a synonym for "indeterminate".

[Indeterminate, according to HL7](https://www.hl7.org/fhir/v2/0078/index.html#v2-0078-IND): _The specified component / analyte, organism or clinical sign could neither be declared positive / negative or detected / not detected by the performed test or procedure._

**Comment by mlterryMitre** [comment]
Yeh, in this case, we clean up NottinghamCombinedGradeNullVS to the normative list and the descriptions exact to what the LA- ID is.

**Comment by markkramerus** [comment]
I checked with Susan, and she says that indeterminate is a test result, not an exception value.  It should be in the answer set.

**Comment by rutemartins** [comment]
CAP will never add indeterminate to their (normative) answer list, since they believe "cannot be determined" better represents the intent. They made it a point to remove it. Is Susan interpreting indeterminate as equivocal?

**Comment by rutemartins** [comment]
My suggested resolution for this issue is to:
 
•	Include “equivocal” in addition to “positive” and “negative” in the value sets representing results for tests that allow for an inconclusive/borderline result (e.g. HER2)
•	For tests represented by LOINC codes with normative answer lists, stick to the answer lists even if they don’t have an explicit indeterminate answer (they’ll usually have one along the lines of “score cannot be determined”)
 
This has implications for the resolution of your ballot comment 16116, since the determination there was to retain #missing_indeterminate from the Observation Value Data Absent Reason value set for exceptionValue in BreastCancerHistologicGrade despite it being missing from the normative answer list associated with that LOINC code. For context, CAP has indicated they have moved away from using the term “indeterminate” precisely because it can have this double meaning. They now use “score cannot be determined”.

@apitkus, any input on this one?

**Comment by rutemartins** [comment]
Per [ASCO/CAP guidelines for PR and ER reporting](https://www.ncbi.nlm.nih.gov/pubmed/20586616), assay interpretation should be provided in one of three mutually exclusive interpretations:

`Positive`
`Negative`
`Uninterpretable` -- in CAP forms represented as `cannot be determined (indeterminate)`

**Notes:**

- Uninterpretable  *is* a null value. The guidelines indicate this value should be used:
> if a sample did not conform to preanalytic specifications of the guideline, was processed using
procedures that did not conform to guideline specifications or the laboratory’s standard operating procedure, or the assay used to analyze the specimen was not validated and controlled as specified in the guideline.

- There is no `Equivocal` for ER and PR status:
> There is no agreement about a range for receptor equivocal, so this term
should not be used.

[ASCO/CAP guidelines on HER2 reporting](http://www.archivesofpathology.org/doi/pdf/10.5858/arpa.2018-0902-SA?code=coap-site) indicate results can be:

`Positive`
`Negative`
`Equivocal`
`Indeterminate` -- in CAP forms represented as `cannot be determined (indeterminate)`

**Note:** Indeterminate *is* a null value:
>Must report HER2 test result as indeterminate if technical issues prevent one or both tests (IHC and ISH) from being reported as positive, negative, or equivocal.

**Comment by rutemartins** [comment]
We will extend this interpretation of `indeterminate` to grade elements: `DCISNuclearGrade`, `BreastCancerHistologicGrade`, `TubuleFormationScore`, `MitoticCountScore`, and `NuclearPleomorphismScore`.

**Comment by apitkus** [comment]
let me review this soon and research some IVD inserts/examples on test result values to help address this.

**Comment by apitkus** [comment]
Worked on a response to this on how these tests are reported.  This is what I had documented thus far.

1.  The laboratory professional can perform ISH or IHC testing, but depending on the result values, they may need to reflex to the other test as indicated in the May 2018 ASCO/CAP guidelines paper.

2. Her2 testing may be performed/reported as qualitative, semi-quantitative or quantitative depending on which IVD vendor test system(s) is/are used by the performing laboratory and which testing methods are utilized.  Here is a list of FDA 510(k) approved methods:  https://www.fda.gov/MedicalDevices/ProductsandMedicalProcedures/InVitroDiagnostics/ucm301431.htm

2.1.  A quantitative test from one vendor offers the HER2/CEP17 ratio testing, which is a dual probe (F)ISH method as recommended by the May 2018 ASCO/CAP guidelines.  The FDA 510(k) approved vendor package insert provides details of the test and how it is to be reported:  https://www.molecular.abbott/sal/30-608377.pdf  This particular test is ONLY to be performed on breast tissue.  

2.2  Another method of dual probe FISH results are required to be reported into new Groups according to the guidelines.   "It is expected that approximately 5% of cases tested by ISH will fall into groups 2, 3, or 4, and 5"    Therefore a qualitative LOINC would be used and unless the LOINC Answers have the ASCO/CAP guidelines groups, LOINC Answers should NOT be used for these test result values.
2.3  Another vendor insert indicates if their initial IHC assay is 2+ (previously equivocal) that they reflex to the dual probe ISH and  "Report as HER2 positive to physician  for Herceptin consideration" 2r Non-Amp Neg as indicated in Figure 1http://www.hsl-ad.com/newsletters/HER2_4B5_Interpretation_Guide.pdf  (One of the reasons I asked the use case is these tests will be set up in the LIS as indicated by the vendor/per accreditation/CLIA requirements.  However, not all the results may be reported back to the ordering provider and thus never seen in the EHR for patient care. It is very common in the laboratory per protocols to dilute quantitative specimens and although an initial high value may be recorded in the LIS, it is the final diluted result which is within instrument reporting range and calculated based upon the dilution, which is actually reported back to the provider for use in patient care.)  

4.  I wouldn't worry about LOINC Answers as the LOINC code can be used without the LOINC Answer.  It's more important for laboratories to report compliant with regulatory requirements, which in some case may require result values that differ than LOINC Answers (they are a guideline, not a requirement and often the LOINC Answers do not contain the complete set of values reported across all test systems using the LOINC code. Folks have been noting across several WGs).  

5.  Responses above are related to ER/PR Her2 testing.    Nottingham Score/grade reporting would follow as indicated in the LOINC Description" a combination of individual scores for the degree of tubule formation [LOINC: 85321-8] , nuclear pleomorphism [LOINC: 44645-0] , and mitotic activity [LOINC: 85300-2] . Each parameter is given a score from 1 to 3, and the final NGH grade is determined based on the sum of those three scores. Grade 1 is assigned for a summed score of 3, 4 or 5; grade 2 is assigned for a summed score of 6 or 7; and grade 3 is assigned for a summed score of 8 or 9. A higher grade is associated with a more aggressive cancer, and patients with grade 3 carcinoma tend to have lower long-term survival rates compared to patients with grade 1"

**Comment by rutemartins** [comment]
Modifying my stance that `indeterminate` **_is_** a null value. Indeterminate **_is not_** a null value because:
1. It asserts that it is not possible to assign any of the other possible results.
2. It does not provide a _reason why_ there is no result.

Ideally, a result of `indeterminate` would be paired with a reason for that result, however, due to FHIR constraints, it is not possible to populate both `value` and `data-absent-reason`. Nonetheless, FHIR allows exception values to be included in the result value set.

Including `indeterminate`/`cannot be determined` in the result value sets is also consistent with CAP guidelines, as well as laboratory reporting requirements.

For histologic and nuclear grade, the rationale is similar. This allows us to keep the LOINC normative answer lists associated with `BreastCancerHistologicGrade`, `TubuleFormationScore`, `MitoticCountScore`, and `NuclearPleomorphismScore` intact.

**Comment by apitkus** [comment]
Concur Indeterminate isn't null.  There are many reasons why a result may not be obtained.  CLIA requires laboratory professionals to indicate "unacceptable" specimen reasons and is supported in V2.51, so reasons should be available from the performing laboratory.  It may be in another field coming into the EHR.  Perhaps it's a field that needs to be incorporated into the model?  

In my clinical practice, I also had a qualitative test system that didn't give a clear positive or negative result.  It may have been due to heterophile antibodies in the patient or other test interferences.  The results was noted as indeterminate as that is the allowed response.  The physician can always repeat a test with a fresh specimen, although harder to do with a biopsy, but a fresh slide can be made from the original tissue block and repeated per the ASCO/CAP guidelines.  They recognize there are a variety of factors of why a result cannot be initially reported.  One where results must not be reported are when quality controls fail (also per CLIA law)).  


In my clinical practice, and as discussed on FHIR Workflow nd LRI calls, there are several decision points at play here with laboratory testing.
1.  Specimen collection, specimen preparation, or testing have not been started by the laboratory and something happens to the specimen (tube broke, tissue lost, tissue not in fixative, specimen at wrong temperature, exposed to light, etc.) At the discretion of the laboratory (director), the order can be canceled due to unacceptable specimen quality (reason given) and the physician is notified to reorder and redraw/recollect the specimen.  The patient is typically not charged for the test, but may be charged for the original venipuncture.  They would be charged for the testing on the recollect.  Nothing is reported in the LIS or EHR.

2. In other cases, the laboratory professional has begun the testing process and the laboratory will charge for the work performed. (the point of no return, fi you will) The original order is processed as normal.  Perhaps the specimen was QNS, and specimen ran out before analysis could be completed.  In the result field, a response such as "*", "N/A" or "see comment" may be entered and reported with a comment line indicating the reason testing could not be completed and a request for a reorder & redraw on a fresh specimen/order.  For irretrievable specimens like tissue, the laboratory may need to request the physician to reorder the testing for billing and to place the final results, but may be able to obtain an aliquot/fresh slice of tissue from another part of the lab to perform the original ordered test.  In some of these cases, indeterminate may also be reported for the original specimen with a comment as to why.  Typically specimen quality issues are handled slightly differently.  Bottom line is laboratories typically build/report responses other than positive/negative for cases such as these as they regularly occur.


The laboratory will determine the response in performing the testing per the manufacturer's instructions as previously shared with examples.  The hormone markers may be performed as separate test results, than the pathology report.  The results may be reported using the biomarker template alone or as a section in the overall pathology report for the specimen with a section on biomarker results and signed off by the pathologist.  


Also would recommend not being dependent on the LOINC Answer lists as I'm unaware of any LIS, or EHR vendors who can currently support their reporting.  That is, if you don't allow the SCT options for result values per MU/MIPS/MACRA vendor certified functionality, nobody may be able to implement your model if limited to LOINC Answers only.
